import type { Metadata } from 'next';
import './globals.css';

import { secondaryFont } from './resources/FontSettings';
import Header from '@/components/ui/Header';

export const metadata: Metadata = {
	title: 'Reason4Hope | By Brenda Silva | Life Coach',
	description: 'Generated by create next app with a touch of Plitz7',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="stylesheet" href="https://use.typekit.net/tlw7mcc.css" />
			</head>
			<body className={`${secondaryFont.variable}`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
